"""add_reading_gaps_and_revision_items

Revision ID: bdcb1a31ba20
Revises: 67fd1e25833c
Create Date: 2026-05-17 05:47:47.465490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdcb1a31ba20'
down_revision: Union[str, None] = '67fd1e25833c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.String(length=100), nullable=False),
    sa.Column('skipped_pages', sa.Text(), nullable=True),
    sa.Column('weak_topics', sa.Text(), nullable=True),
    sa.Column('gap_score', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_gaps_book_id'), 'reading_gaps', ['book_id'], unique=False)
    op.create_index(op.f('ix_reading_gaps_id'), 'reading_gaps', ['id'], unique=False)
    op.create_index(op.f('ix_reading_gaps_user_id'), 'reading_gaps', ['user_id'], unique=False)
    op.create_table('revision_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('page_refs', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('last_revised', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revision_items_book_id'), 'revision_items', ['book_id'], unique=False)
    op.create_index(op.f('ix_revision_items_id'), 'revision_items', ['id'], unique=False)
    op.create_index(op.f('ix_revision_items_user_id'), 'revision_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revision_items_user_id'), table_name='revision_items')
    op.drop_index(op.f('ix_revision_items_id'), table_name='revision_items')
    op.drop_index(op.f('ix_revision_items_book_id'), table_name='revision_items')
    op.drop_table('revision_items')
    op.drop_index(op.f('ix_reading_gaps_user_id'), table_name='reading_gaps')
    op.drop_index(op.f('ix_reading_gaps_id'), table_name='reading_gaps')
    op.drop_index(op.f('ix_reading_gaps_book_id'), table_name='reading_gaps')
    op.drop_table('reading_gaps')
    # ### end Alembic commands ###
