"""Change book_id to string

Revision ID: f440b6e9b145
Revises: 3ea91410452f
Create Date: 2026-05-12 13:28:29.180046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f440b6e9b145'
down_revision: Union[str, None] = '3ea91410452f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookmarks_book_id_fkey', 'bookmarks', type_='foreignkey')
    op.alter_column('bookmarks', 'book_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_bookmarks_book_id'), 'bookmarks', ['book_id'], unique=False)
    
    op.drop_constraint('highlights_book_id_fkey', 'highlights', type_='foreignkey')
    op.alter_column('highlights', 'book_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_highlights_book_id'), 'highlights', ['book_id'], unique=False)
    
    op.drop_constraint('notes_book_id_fkey', 'notes', type_='foreignkey')
    op.alter_column('notes', 'book_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_notes_book_id'), 'notes', ['book_id'], unique=False)
    
    op.drop_constraint('reading_progress_book_id_fkey', 'reading_progress', type_='foreignkey')
    op.alter_column('reading_progress', 'book_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('reading_progress_book_id_fkey', 'reading_progress', 'books', ['book_id'], ['id'])
    op.alter_column('reading_progress', 'book_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_foreign_key('notes_book_id_fkey', 'notes', 'books', ['book_id'], ['id'])
    op.drop_index(op.f('ix_notes_book_id'), table_name='notes')
    op.alter_column('notes', 'book_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_foreign_key('highlights_book_id_fkey', 'highlights', 'books', ['book_id'], ['id'])
    op.drop_index(op.f('ix_highlights_book_id'), table_name='highlights')
    op.alter_column('highlights', 'book_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_foreign_key('bookmarks_book_id_fkey', 'bookmarks', 'books', ['book_id'], ['id'])
    op.drop_index(op.f('ix_bookmarks_book_id'), table_name='bookmarks')
    op.alter_column('bookmarks', 'book_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
